import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  BellRing,
  Boxes,
  Cloud,
  Database,
  FileStack,
  HardDrive,
  LayoutDashboard,
  MessageSquareText,
  Network,
  RadioTower,
  RectangleHorizontal,
  Server,
  ShieldCheck,
  Sparkles,
  TimerReset,
  Workflow,
} from 'lucide-react';
import type {
  PipelineNodeCategory,
  PipelineNodeProvider,
  PipelineNodeRole,
  PipelineNodeShapeKind,
} from '@/types/practice';

export type ArchitectureShapeDefinition = {
  id: string;
  label: string;
  keywords: string[];
  provider: PipelineNodeProvider;
  category: PipelineNodeCategory;
  shapeKind: PipelineNodeShapeKind;
  role: PipelineNodeRole;
  icon: LucideIcon;
  tone: 'gold' | 'blue' | 'slate';
  hint: string;
  configSummary: string;
  width: number;
  height: number;
};

export const pipelineShapeGroups: Array<{
  id: string;
  title: string;
  description: string;
  items: ArchitectureShapeDefinition[];
}> = [
  {
    id: 'storage',
    title: 'Storage & databases',
    description: 'Landing, warehouse, and durable data-store shapes.',
    items: [
      {
        id: 'shape-s3',
        label: 'S3',
        keywords: ['aws', 'storage', 'bucket', 'landing', 'object'],
        provider: 'aws',
        category: 'storage',
        shapeKind: 's3',
        role: 'source',
        icon: HardDrive,
        tone: 'blue',
        hint: 'Object storage landing zone or raw bronze bucket.',
        configSummary: 'orders/raw/daily',
        width: 194,
        height: 110,
      },
      {
        id: 'shape-redshift',
        label: 'Redshift',
        keywords: ['aws', 'redshift', 'warehouse', 'analytics', 'mart'],
        provider: 'aws',
        category: 'storage',
        shapeKind: 'redshift',
        role: 'sink',
        icon: Database,
        tone: 'blue',
        hint: 'Analytics warehouse or downstream serving target.',
        configSummary: 'analytics.orders_daily',
        width: 194,
        height: 110,
      },
      {
        id: 'shape-warehouse',
        label: 'Warehouse',
        keywords: ['warehouse', 'lakehouse', 'analytics', 'serving'],
        provider: 'platform',
        category: 'storage',
        shapeKind: 'warehouse',
        role: 'sink',
        icon: FileStack,
        tone: 'gold',
        hint: 'Generic analytics warehouse or lakehouse destination.',
        configSummary: 'curated mart',
        width: 198,
        height: 112,
      },
      {
        id: 'shape-database',
        label: 'Database',
        keywords: ['database', 'postgres', 'mysql', 'oltp', 'source'],
        provider: 'platform',
        category: 'storage',
        shapeKind: 'database',
        role: 'source',
        icon: Database,
        tone: 'slate',
        hint: 'Operational database source or stateful store.',
        configSummary: 'orders table',
        width: 194,
        height: 110,
      },
    ],
  },
  {
    id: 'compute',
    title: 'Compute & processing',
    description: 'Execution runtimes and transformation layers.',
    items: [
      {
        id: 'shape-ec2',
        label: 'EC2 / compute',
        keywords: ['aws', 'ec2', 'compute', 'job', 'worker'],
        provider: 'aws',
        category: 'compute',
        shapeKind: 'ec2',
        role: 'transform',
        icon: Server,
        tone: 'blue',
        hint: 'General compute box for jobs, workers, or custom runtimes.',
        configSummary: 'python transform',
        width: 204,
        height: 112,
      },
      {
        id: 'shape-spark',
        label: 'Spark',
        keywords: ['spark', 'batch', 'transform', 'compute'],
        provider: 'platform',
        category: 'compute',
        shapeKind: 'spark',
        role: 'transform',
        icon: Sparkles,
        tone: 'gold',
        hint: 'Distributed batch transformation stage.',
        configSummary: 'daily enrichment job',
        width: 194,
        height: 110,
      },
      {
        id: 'shape-flink',
        label: 'Flink',
        keywords: ['flink', 'stream', 'processing', 'window'],
        provider: 'platform',
        category: 'compute',
        shapeKind: 'flink',
        role: 'transform',
        icon: Activity,
        tone: 'gold',
        hint: 'Streaming or low-latency processing runtime.',
        configSummary: 'stream aggregation',
        width: 194,
        height: 110,
      },
      {
        id: 'shape-batch',
        label: 'Batch job',
        keywords: ['batch', 'job', 'etl', 'transform'],
        provider: 'neutral',
        category: 'compute',
        shapeKind: 'batch-job',
        role: 'transform',
        icon: Workflow,
        tone: 'slate',
        hint: 'Generic ETL or orchestrated transform step.',
        configSummary: 'daily orders ETL',
        width: 198,
        height: 112,
      },
      {
        id: 'shape-cluster',
        label: 'Cluster / platform',
        keywords: ['cluster', 'platform', 'kubernetes', 'runtime'],
        provider: 'platform',
        category: 'compute',
        shapeKind: 'cluster',
        role: 'support',
        icon: Boxes,
        tone: 'slate',
        hint: 'Higher-level runtime or platform boundary.',
        configSummary: 'shared compute plane',
        width: 216,
        height: 118,
      },
    ],
  },
  {
    id: 'streaming',
    title: 'Streaming & orchestration',
    description: 'Event flow, scheduling, and orchestration controls.',
    items: [
      {
        id: 'shape-kafka',
        label: 'Kafka / stream',
        keywords: ['kafka', 'stream', 'broker', 'queue', 'transport'],
        provider: 'platform',
        category: 'streaming',
        shapeKind: 'kafka',
        role: 'source',
        icon: RadioTower,
        tone: 'blue',
        hint: 'Streaming transport or event broker entry point.',
        configSummary: 'orders topic',
        width: 208,
        height: 112,
      },
      {
        id: 'shape-scheduler',
        label: 'Scheduler trigger',
        keywords: ['schedule', 'cron', 'trigger', 'orchestration'],
        provider: 'neutral',
        category: 'streaming',
        shapeKind: 'scheduler-trigger',
        role: 'scheduler-trigger',
        icon: TimerReset,
        tone: 'slate',
        hint: 'Root trigger that starts a scheduled run.',
        configSummary: '0 3 * * *',
        width: 214,
        height: 112,
      },
      {
        id: 'shape-workflow',
        label: 'Workflow / orchestrator',
        keywords: ['workflow', 'orchestrator', 'dag', 'airflow'],
        provider: 'platform',
        category: 'streaming',
        shapeKind: 'workflow',
        role: 'branch',
        icon: Workflow,
        tone: 'slate',
        hint: 'Branching or orchestration-aware control node.',
        configSummary: 'fan-out by domain',
        width: 222,
        height: 114,
      },
    ],
  },
  {
    id: 'analytics',
    title: 'Analytics & observability',
    description: 'Reporting, quality, and failure-response shapes.',
    items: [
      {
        id: 'shape-dashboard',
        label: 'Dashboard',
        keywords: ['dashboard', 'bi', 'report', 'analytics', 'looker'],
        provider: 'platform',
        category: 'analytics',
        shapeKind: 'dashboard',
        role: 'support',
        icon: LayoutDashboard,
        tone: 'blue',
        hint: 'BI or reporting consumer of the pipeline output.',
        configSummary: 'freshness board',
        width: 202,
        height: 112,
      },
      {
        id: 'shape-alert',
        label: 'Alert',
        keywords: ['alert', 'pagerduty', 'slack', 'incident', 'failure'],
        provider: 'neutral',
        category: 'analytics',
        shapeKind: 'alert',
        role: 'alert',
        icon: BellRing,
        tone: 'gold',
        hint: 'Failure or SLA escalation target.',
        configSummary: 'pager duty route',
        width: 186,
        height: 108,
      },
      {
        id: 'shape-quality',
        label: 'Quality check',
        keywords: ['quality', 'dq', 'validation', 'checks', 'tests'],
        provider: 'neutral',
        category: 'analytics',
        shapeKind: 'quality-check',
        role: 'quality-check',
        icon: ShieldCheck,
        tone: 'gold',
        hint: 'Data-quality gate before publish or alerting.',
        configSummary: 'row-count + null checks',
        width: 208,
        height: 114,
      },
      {
        id: 'shape-monitor',
        label: 'Monitor / logging',
        keywords: ['monitor', 'logging', 'metrics', 'observability'],
        provider: 'platform',
        category: 'analytics',
        shapeKind: 'monitor',
        role: 'support',
        icon: Activity,
        tone: 'slate',
        hint: 'Context-only observability or monitoring surface.',
        configSummary: 'ops telemetry',
        width: 208,
        height: 112,
      },
    ],
  },
  {
    id: 'boundaries',
    title: 'Cloud / platform grouping',
    description: 'Provider-aware boundaries and architecture notes.',
    items: [
      {
        id: 'shape-note',
        label: 'Note',
        keywords: ['note', 'comment', 'reasoning', 'brainstorm'],
        provider: 'neutral',
        category: 'note',
        shapeKind: 'note',
        role: 'support',
        icon: MessageSquareText,
        tone: 'blue',
        hint: 'Capture assumptions, tradeoffs, or interview talk track.',
        configSummary: 'reasoning note',
        width: 198,
        height: 114,
      },
      {
        id: 'shape-aws-boundary',
        label: 'AWS boundary',
        keywords: ['aws', 'boundary', 'account', 'cloud'],
        provider: 'aws',
        category: 'boundary',
        shapeKind: 'aws-boundary',
        role: 'support',
        icon: Cloud,
        tone: 'blue',
        hint: 'Group AWS-owned services into one bounded context.',
        configSummary: 'prod analytics account',
        width: 246,
        height: 138,
      },
      {
        id: 'shape-azure-boundary',
        label: 'Azure boundary',
        keywords: ['azure', 'boundary', 'subscription', 'cloud'],
        provider: 'azure',
        category: 'boundary',
        shapeKind: 'azure-boundary',
        role: 'support',
        icon: Network,
        tone: 'blue',
        hint: 'Group Azure-owned services into one bounded context.',
        configSummary: 'core data subscription',
        width: 246,
        height: 138,
      },
      {
        id: 'shape-platform-boundary',
        label: 'Platform boundary',
        keywords: ['platform', 'boundary', 'domain', 'context'],
        provider: 'platform',
        category: 'boundary',
        shapeKind: 'platform-boundary',
        role: 'support',
        icon: Boxes,
        tone: 'gold',
        hint: 'Frame a platform or lifecycle area around related nodes.',
        configSummary: 'analytics platform',
        width: 240,
        height: 136,
      },
      {
        id: 'shape-rectangle',
        label: 'Rectangle',
        keywords: ['rectangle', 'generic', 'service', 'process'],
        provider: 'neutral',
        category: 'basics',
        shapeKind: 'rectangle',
        role: 'support',
        icon: RectangleHorizontal,
        tone: 'slate',
        hint: 'Neutral generic process or service block.',
        configSummary: 'service block',
        width: 194,
        height: 108,
      },
    ],
  },
];

export const pipelineShapeIndex = pipelineShapeGroups.flatMap((group) => group.items);
